framework:
    messenger:

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'shop_ex'
                        type: direct
                        default_publish_routing_key: 'products_create'
                    queues:
                        products:
                            binding_keys: ['products_create']

                retry_strategy:
                    max_retries: 3
                    delay: 1000

            sync: 'sync://'

        routing:
            'App\Application\Shared\Messenger\Contract\AsyncMessageInterface': async
