security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Domain\User\Entity\User: 'auto'

    providers:
        user_provider:
            entity:
                class: App\Domain\User\Entity\User
                property: phone

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        token:
            pattern: ^/api/v1/auth
            security: false

        api:
            pattern: ^/api/v1
            stateless: true
            provider: user_provider
            jwt: ~

        main:
            lazy: true
            provider: user_provider

    access_control:
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/user/create, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/user/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: bcrypt
